name: On push to master branch

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: thumbnailone

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:staging .

      - name: Push Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:staging
